version: '3'

services:
  web:
    image: nginx:latest
    container_name: web_container
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - api
    networks:
      - my_network
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: api_container
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    networks:
      - my_network
  mysql:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 1234
      MYSQL_USER: admin
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my_network
  soketi:
    image: 'quay.io/soketi/soketi:1.4-16-alpine'
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_APP_ID: 'app-id'
      SOKETI_APP_KEY: 'app-key'
      SOKETI_APP_SECRET: 'app-secret'
    ports:
      - '6001:6001'
    networks:
      - my_network
networks:
  my_network:
